[tool.black]
target-version = ["py311"]
[tool.ruff]
# Enable Pyflakes `E` and `F` codes by default.
select = ["E", "F"]
ignore = ["E501", "E741","F403","F405"]
extend-exclude = ["apps.py", "migrations"]
force-exclude = true
[tool.bandit]
exclude_dirs = ["tests"]
[tool.isort]
